name: On Pull Request

on: [pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js (v16.13)
      uses: actions/setup-node@v3
      with:
        node-version: 16.13

    - name: Install Dependencies
      run: npm ci

    - name: Building app
      run: npm run build

  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js (v18.15)
      uses: actions/setup-node@v3
      with:
        node-version: 16.13

    - name: Install Dependencies
      run: npm ci

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: '6.0'
        mongodb-username: base39
        mongodb-password: base39
        mongodb-db: base39

    - name: Run Test
      run: npm run test:coverage
      env:
        ENVIRONMENT: development
        MONGO_URL: mongodb://base39:base39@localhost:27017/base39?retryWrites=true
        HOST: localhost
        PORT: 8000

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: |
          ${{ github.workspace }}/coverage
